spring.application.name=demo
spring.docker.compose.enabled=false
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=5388995d2bbae1
spring.mail.password=e2dc26a1383b5c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# File upload configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
! spring h2 sql server dependencies 
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

!  Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
